"use client";

import autoTable from "jspdf-autotable";
import { jsPDF } from "jspdf";
import { PKB, JasaPKB, SparepartPKB } from "@prisma/client";
import { forwardRef, ReactInstance, useRef } from "react";
import { useReactToPrint } from "react-to-print";
import Html2Pdf from "js-html2pdf";

export const Invoice = forwardRef<HTMLDivElement>((props, ref) => {
  return (
    <div className="App" ref={ref}>
      <div className="header">
        <span className="logo">REAs</span>
        <nav>
          <span>Blog</span>
          <span>Categories</span>
          <span>Tags</span>
        </nav>
      </div>
      <div className="hero-section">
        <h1>The Joys of Buying Over Building</h1>
      </div>
      <main>
        <h2 className="features-title">Some features</h2>
        <div className="features">
          <span className="active">House 1</span>
          <span>House 2</span>
          <span>House 3</span>
        </div>
        <p>
          In the grand game of acquiring a new abode, the age-old debate between
          buying an existing house and building a brand-new one continues to
          captivate prospective homeowners. Both options have of opting for a
          pre-built dwelling.
        </p>
        <p>
          history. Buying a house often means settling into an established
          community, complete with charming local spots and friendly neighbors.
          Sure, you might not have personally picked out every stories embedded
          in its walls and the quirks that come with a house
        </p>
        <p>
          or swaying to the rhythm of your own construction symphony, the
          decision between buying and building is a personal one. But hey, and
          immediately feeling at home – no hard hat required.
        </p>
        <p className="lower">Article generated by ChatGPT</p>
      </main>
    </div>
  );
});

Invoice.displayName = "Invoice";

export const GeneratePDF = () =>
  // pkb: PKB & { jasaPKB: JasaPKB[]; sparepartPKB: SparepartPKB[] },
  {
    const componentRef = useRef(null);
    const handlePrint = useReactToPrint({
      content: () => componentRef.current,
      print: async (printIframe) => {
        const document = printIframe.contentDocument;
        if (document) {
          const html = document.getElementsByClassName("App")[0];
          const options = {
            margin: 0,
            filename: "the-joys-of-buying-over-building.pdf",
            jsPDF: { unit: "mm", format: "a4", orientation: "landspace" },
          };
          const exporter = new Html2Pdf(html, options);
          await exporter.getPdf(options);
        }
      },
    });

    return (
      <div>
        <Invoice ref={componentRef} />
        <button onClick={handlePrint}>Print article</button>
      </div>
    );
  };
