export const data = [
  {
    action: 0,
    id: 19,
    kodeKaryawan: "K0019",
    namaKaryawan: "AL HUDA",
    jenisKelamin: "L",
    alamat: "DUKUHAN BANYUANYAR RT 002 RW 012 BANYUANYAR BANJARSARI SURAKARTA",
    city: { id: 1574, text: "KOTA SURAKARTA", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "089531187226",
    kTP: "3372050311000001",
    tanggalMasuk: "2023-04-01 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 37374,
      provinceID: 13,
      cityID: 1574,
      zipCode: "57137",
      kelurahan: "Banyuanyar",
      kecamatan: "Banjarsari",
      kabupaten: "KOTA SURAKARTA",
      ahmCode: "3372050013",
      bpsCode: "3372050013",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "SURAKARTA",
    tanggalLahir: "2000-11-03 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 1,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 0,
    nik: "0",
    listJabatan: [{ jabatanID: 1, jabatan: "Asisten Mekanik" }],
    listPayroll: [
      { payrollID: 91, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 92,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 93,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 94,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 95, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: true,
  },
  {
    action: 0,
    id: 18,
    kodeKaryawan: "K0018",
    namaKaryawan: "DANUNG MAFUAD",
    jenisKelamin: "L",
    alamat: "JATITENGAH RT 011 RW 000 JATITENGAH SUKODONO SRAGEN",
    city: { id: 1508, text: "KAB. SRAGEN", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "081326583751",
    kTP: ".",
    tanggalMasuk: "2022-06-10 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 41320,
      provinceID: 13,
      cityID: 1508,
      zipCode: "57263",
      kelurahan: "Jatitengah",
      kecamatan: "Sukodono",
      kabupaten: "KAB. SRAGEN",
      ahmCode: "3314170002",
      bpsCode: "3314170002",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "SRAGEN",
    tanggalLahir: "2004-09-10 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 1,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 1,
    nik: "588189",
    listJabatan: [{ jabatanID: 5, jabatan: "Mekanik" }],
    listPayroll: [
      { payrollID: 86, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 87,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 88,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 89,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 90, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: true,
  },
  {
    action: 0,
    id: 17,
    kodeKaryawan: "K0017",
    namaKaryawan: "OKI SAPUTRA",
    jenisKelamin: "L",
    alamat: "JATITENGAH RT 012 RW 000 JATITENGAH SUKODONO SRAGEN",
    city: { id: 1508, text: "KAB. SRAGEN", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "082134297195",
    kTP: ".",
    tanggalMasuk: "2022-05-23 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 41320,
      provinceID: 13,
      cityID: 1508,
      zipCode: "57263",
      kelurahan: "Jatitengah",
      kecamatan: "Sukodono",
      kabupaten: "KAB. SRAGEN",
      ahmCode: "3314170002",
      bpsCode: "3314170002",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "SRAGEN",
    tanggalLahir: "2001-10-02 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 0,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 1,
    nik: "586180",
    listJabatan: [{ jabatanID: 5, jabatan: "Mekanik" }],
    listPayroll: [
      { payrollID: 81, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 82,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 83,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 84,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 85, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: true,
  },
  {
    action: 0,
    id: 16,
    kodeKaryawan: "K0016",
    namaKaryawan: "ELLY KARDINAWATI",
    jenisKelamin: "P",
    alamat: "KRAJAN RT 004 RW 001 SUMBER BANJARSARI SURAKARTA",
    city: { id: 1574, text: "KOTA SURAKARTA", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "085868411014",
    kTP: ".",
    tanggalMasuk: "2020-11-01 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 37377,
      provinceID: 13,
      cityID: 1574,
      zipCode: "57138",
      kelurahan: "Sumber",
      kecamatan: "Banjarsari",
      kabupaten: "KOTA SURAKARTA",
      ahmCode: "3372050012",
      bpsCode: "3372050010",
      rowStatus: 0,
    },
    email: "ellysolo033@gmail.com",
    catatan: "",
    tempatLahir: "SURAKARTA",
    tanggalLahir: "1992-01-23 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 0,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 0,
    nik: "18",
    listJabatan: [{ jabatanID: 10, jabatan: "Partcounter" }],
    listPayroll: [
      { payrollID: 76, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 77,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 78,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 79,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 80, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: true,
  },
  {
    action: 0,
    id: 15,
    kodeKaryawan: "K0015",
    namaKaryawan: "YOSEF MARYANTO",
    jenisKelamin: "L",
    alamat: "JL PAJAJARAN I RT 001 RW 013 SUMBER BANJARSARI SURAKARTA",
    city: { id: 1574, text: "KOTA SURAKARTA", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "085641555246",
    kTP: "3372052003720006",
    tanggalMasuk: "2005-09-08 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 37377,
      provinceID: 13,
      cityID: 1574,
      zipCode: "57138",
      kelurahan: "Sumber",
      kecamatan: "Banjarsari",
      kabupaten: "KOTA SURAKARTA",
      ahmCode: "3372050012",
      bpsCode: "3372050010",
      rowStatus: 0,
    },
    email: "",
    catatan: ".",
    tempatLahir: "SURAKARTA",
    tanggalLahir: "1972-03-20 00:00:00",
    agama: 2,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 1,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 0,
    nik: "017",
    listJabatan: [{ jabatanID: 2, jabatan: "FrontDesk" }],
    listPayroll: [
      { payrollID: 71, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 72,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 73,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 74,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 75, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [
      {
        trainingLevelMekanikID: 1,
        trainingLevel: "Training PAA (Pelatihan Administrasi AHASS)",
        jabatanID: 2,
      },
    ],
    aktif: true,
  },
  {
    action: 0,
    id: 14,
    kodeKaryawan: "K0014",
    namaKaryawan: "ARI KRISTIYAWATI",
    jenisKelamin: "P",
    alamat: "GEDONGAN RT 005 RW 006 GEDONGAN COLOMADU KARANGANYAR",
    city: { id: 1537, text: "KAB. KARANGANYAR", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "085842438096",
    kTP: ".",
    tanggalMasuk: "2015-12-14 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 41556,
      provinceID: 13,
      cityID: 1537,
      zipCode: "57173",
      kelurahan: "Gedongan",
      kecamatan: "Colomadu",
      kabupaten: "KAB. KARANGANYAR",
      ahmCode: "3313120008",
      bpsCode: "3313120008",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "SURAKARTA",
    tanggalLahir: "1989-01-02 00:00:00",
    agama: 2,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 1,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 0,
    nik: "16",
    listJabatan: [
      { jabatanID: 14, jabatan: "Admin" },
      { jabatanID: 2, jabatan: "FrontDesk" },
    ],
    listPayroll: [
      { payrollID: 66, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 67,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 68,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 69,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 70, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [
      {
        trainingLevelMekanikID: 1,
        trainingLevel: "Training PAA (Pelatihan Administrasi AHASS)",
        jabatanID: 2,
      },
    ],
    aktif: true,
  },
  {
    action: 0,
    id: 13,
    kodeKaryawan: "K0013",
    namaKaryawan: "SARDIANTO",
    jenisKelamin: "L",
    alamat: "BANYUANYAR RT 004 RW 009 BANYUANYAR BANJARSARI SURAKARTA",
    city: { id: 1574, text: "KOTA SURAKARTA", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "0882005351961",
    kTP: "801114410109",
    tanggalMasuk: "2004-05-18 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 37374,
      provinceID: 13,
      cityID: 1574,
      zipCode: "57137",
      kelurahan: "Banyuanyar",
      kecamatan: "Banjarsari",
      kabupaten: "KOTA SURAKARTA",
      ahmCode: "3372050013",
      bpsCode: "3372050013",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "SURAKARTA",
    tanggalLahir: "1980-11-06 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 0,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 0,
    nik: "15",
    listJabatan: [
      { jabatanID: 4, jabatan: "Kepala Mekanik" },
      { jabatanID: 12, jabatan: "Mekanik Final Inspector" },
      { jabatanID: 7, jabatan: "Service Advisor" },
    ],
    listPayroll: [
      { payrollID: 61, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 62,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 63,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 64,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 65, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: true,
  },
  {
    action: 0,
    id: 12,
    kodeKaryawan: "K0012",
    namaKaryawan: "EKBAL YAINURI",
    jenisKelamin: "L",
    alamat: "BOTOREJO RT 007 RW 001 TEGALOMBO KALIJAMBE SRAGEN",
    city: { id: 1508, text: "KAB. SRAGEN", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "081548240032",
    kTP: "3314180601970001",
    tanggalMasuk: "2014-11-05 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 41485,
      provinceID: 13,
      cityID: 1508,
      zipCode: "57275",
      kelurahan: "Tegalombo",
      kecamatan: "Kalijambe",
      kabupaten: "KAB. SRAGEN",
      ahmCode: "3314010008",
      bpsCode: "3314010014",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "SRAGEN",
    tanggalLahir: "1997-01-06 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 0,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 0,
    nik: "013",
    listJabatan: [{ jabatanID: 2, jabatan: "FrontDesk" }],
    listPayroll: [
      { payrollID: 56, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 57,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 58,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 59,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 60, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [
      {
        trainingLevelMekanikID: 1,
        trainingLevel: "Training PAA (Pelatihan Administrasi AHASS)",
        jabatanID: 2,
      },
    ],
    aktif: true,
  },
  {
    action: 0,
    id: 11,
    kodeKaryawan: "K0011",
    namaKaryawan: "IRDIANTO",
    jenisKelamin: "L",
    alamat: "CINDEREJO LOR RT 001 RW 004 GILINGAN BANJARSARI SURAKARTA",
    city: { id: 1574, text: "KOTA SURAKARTA", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "085643354785",
    kTP: ".",
    tanggalMasuk: "2013-03-04 00:00:00",
    tanggalBerhenti: "2023-05-01 00:00:00",
    area: {
      id: 37379,
      provinceID: 13,
      cityID: 1574,
      zipCode: "57134",
      kelurahan: "Gilingan",
      kecamatan: "Banjarsari",
      kabupaten: "KOTA SURAKARTA",
      ahmCode: "3372050003",
      bpsCode: "3372050008",
      rowStatus: 0,
    },
    email: "",
    catatan: ".",
    tempatLahir: "SURAKARTA",
    tanggalLahir: "1951-10-01 23:30:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 0,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 0,
    nik: "0",
    listJabatan: [{ jabatanID: 4, jabatan: "Kepala Mekanik" }],
    listPayroll: [
      { payrollID: 51, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 52,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 53,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 54,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 55, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: false,
  },
  {
    action: 0,
    id: 10,
    kodeKaryawan: "K0010",
    namaKaryawan: "ANTON JANUAR WIBOWO",
    jenisKelamin: "L",
    alamat: "PEPE RT 002 RW 009 GEDONGAN COLOMADU KARANGANYAR",
    city: { id: 1537, text: "KAB. KARANGANYAR", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "089510488260",
    kTP: "12",
    tanggalMasuk: "2021-04-11 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 41556,
      provinceID: 13,
      cityID: 1537,
      zipCode: "57173",
      kelurahan: "Gedongan",
      kecamatan: "Colomadu",
      kabupaten: "KAB. KARANGANYAR",
      ahmCode: "3313120008",
      bpsCode: "3313120008",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "KARANGANYAR",
    tanggalLahir: "2021-07-06 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 1,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 0,
    nik: "12",
    listJabatan: [{ jabatanID: 1, jabatan: "Asisten Mekanik" }],
    listPayroll: [
      { payrollID: 46, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 47,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 48,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 49,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 50, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: true,
  },
  {
    action: 0,
    id: 9,
    kodeKaryawan: "K0009",
    namaKaryawan: "DIKY RAMADHAN",
    jenisKelamin: "L",
    alamat: "EROMOKO KULON RT 003 RW 002 EROMOKO EROMOKO WONOGIRI",
    city: { id: 1565, text: "KAB. WONOGIRI", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "082145497491",
    kTP: "3312080112000001",
    tanggalMasuk: "2019-05-01 00:00:00",
    tanggalBerhenti: "2022-06-03 00:00:00",
    area: {
      id: 41854,
      provinceID: 13,
      cityID: 1565,
      zipCode: "57663",
      kelurahan: "Eromoko",
      kecamatan: "Eromoko",
      kabupaten: "KAB. WONOGIRI",
      ahmCode: "3312080011",
      bpsCode: "3312100011",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "EROMOKO",
    tanggalLahir: "2000-12-01 00:00:00",
    agama: 1,
    berlakuKTP: "2022-06-03 00:00:00",
    kebangsaan: 1,
    statusKawin: 1,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 1,
    nik: "K0009",
    listJabatan: [{ jabatanID: 5, jabatan: "Mekanik" }],
    listPayroll: [
      { payrollID: 41, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 42,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 43,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 44,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 45, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [
      {
        trainingLevelMekanikID: 10,
        trainingLevel: "Training Technical Level 1",
        jabatanID: 5,
      },
    ],
    aktif: false,
  },
  {
    action: 0,
    id: 8,
    kodeKaryawan: "K0008",
    namaKaryawan: "SURYA DANA",
    jenisKelamin: "L",
    alamat: "BULAKREJO TANGKIL SRAGEN",
    city: { id: 1508, text: "KAB. SRAGEN", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "085713891479",
    kTP: ".",
    tanggalMasuk: "2019-05-01 00:00:00",
    tanggalBerhenti: "2020-05-01 00:00:00",
    area: {
      id: 41309,
      provinceID: 13,
      cityID: 1508,
      zipCode: "57262",
      kelurahan: "Gesi",
      kecamatan: "Gesi",
      kabupaten: "KAB. SRAGEN",
      ahmCode: "3314180004",
      bpsCode: "3314180004",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: ".",
    tanggalLahir: "2001-05-30 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 1,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 1,
    nik: ".",
    listJabatan: [{ jabatanID: 5, jabatan: "Mekanik" }],
    listPayroll: [
      { payrollID: 36, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 37,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 38,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 39,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 40, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: false,
  },
  {
    action: 0,
    id: 7,
    kodeKaryawan: "K0007",
    namaKaryawan: "SARJONO",
    jenisKelamin: "L",
    alamat: "WATES RT 002 RW 010 JATEN JATEN KARANGANYAR",
    city: { id: 1537, text: "KAB. KARANGANYAR", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "082221075225",
    kTP: "3313112307810001",
    tanggalMasuk: "2011-07-07 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 41569,
      provinceID: 13,
      cityID: 1537,
      zipCode: "57731",
      kelurahan: "Jaten",
      kecamatan: "Jaten",
      kabupaten: "KAB. KARANGANYAR",
      ahmCode: "3313110003",
      bpsCode: "3313110003",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "KARANGANYAR",
    tanggalLahir: "1981-07-23 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 0,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 0,
    nik: "0008",
    listJabatan: [
      { jabatanID: 7, jabatan: "Service Advisor" },
      { jabatanID: 12, jabatan: "Mekanik Final Inspector" },
    ],
    listPayroll: [
      { payrollID: 31, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 32,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 33,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 34,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 35, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: true,
  },
  {
    action: 0,
    id: 6,
    kodeKaryawan: "K0006",
    namaKaryawan: "SRI WIDODO",
    jenisKelamin: "L",
    alamat: "NGEMPLAK",
    city: { id: 1615, text: "KAB. BOYOLALI", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "082221075227",
    kTP: "3314160611890001",
    tanggalMasuk: "2011-07-01 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 42646,
      provinceID: 13,
      cityID: 1615,
      zipCode: "57375",
      kelurahan: "Donohudan",
      kecamatan: "Ngemplak",
      kabupaten: "KAB. BOYOLALI",
      ahmCode: "3309110005",
      bpsCode: "3309110005",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "NGEMPLAK",
    tanggalLahir: "2011-11-24 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 0,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 0,
    nik: "0006",
    listJabatan: [
      { jabatanID: 6, jabatan: "Salesman" },
      { jabatanID: 4, jabatan: "Kepala Mekanik" },
      { jabatanID: 12, jabatan: "Mekanik Final Inspector" },
    ],
    listPayroll: [
      { payrollID: 26, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 27,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 28,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 29,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 30, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: true,
  },
  {
    action: 0,
    id: 5,
    kodeKaryawan: "K0005",
    namaKaryawan: "HENGKI IRAWAN",
    jenisKelamin: "L",
    alamat: "MLALE",
    city: { id: 1508, text: "KAB. SRAGEN", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "082243315166",
    kTP: "3314202312990001",
    tanggalMasuk: "2017-07-19 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 41296,
      provinceID: 13,
      cityID: 1508,
      zipCode: "57256",
      kelurahan: "Mlale",
      kecamatan: "Jenar",
      kabupaten: "KAB. SRAGEN",
      ahmCode: "3314200003",
      bpsCode: "3314200003",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "SRAGEN",
    tanggalLahir: "1999-12-23 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 0,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 1,
    nik: "0005",
    listJabatan: [{ jabatanID: 5, jabatan: "Mekanik" }],
    listPayroll: [
      { payrollID: 21, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 22,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 23,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 24,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 25, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: true,
  },
  {
    action: 0,
    id: 4,
    kodeKaryawan: "K0004",
    namaKaryawan: "ERWAN AGUS PRANOTO",
    jenisKelamin: "L",
    alamat: "GUMUKREJO",
    city: { id: 1615, text: "KAB. BOYOLALI", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "082221075255",
    kTP: "3309120908969007",
    tanggalMasuk: "2017-10-17 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 42621,
      provinceID: 13,
      cityID: 1615,
      zipCode: "57377",
      kelurahan: "Simo",
      kecamatan: "Simo",
      kabupaten: "KAB. BOYOLALI",
      ahmCode: "3309130005",
      bpsCode: "3309130005",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "BOYOLALI",
    tanggalLahir: "1996-09-09 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 0,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 1,
    nik: "0004",
    listJabatan: [{ jabatanID: 5, jabatan: "Mekanik" }],
    listPayroll: [
      { payrollID: 16, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 17,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 18,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 19,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 20, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: false,
  },
  {
    action: 0,
    id: 3,
    kodeKaryawan: "K0003",
    namaKaryawan: "HAFIED FRENDIANTO",
    jenisKelamin: "L",
    alamat: "NGENDEN",
    city: { id: 1641, text: "KAB. SUKOHARJO", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "082243315105",
    kTP: "3311103110940003",
    tanggalMasuk: "2016-07-06 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 41989,
      provinceID: 13,
      cityID: 1641,
      zipCode: "57556",
      kelurahan: "Gentan",
      kecamatan: "Baki",
      kabupaten: "KAB. SUKOHARJO",
      ahmCode: "3311100013",
      bpsCode: "3311100013",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "surakarta",
    tanggalLahir: "1994-10-31 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 0,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 1,
    nik: "0003",
    listJabatan: [{ jabatanID: 5, jabatan: "Mekanik" }],
    listPayroll: [
      { payrollID: 11, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 12,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 13,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 14,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 15, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: false,
  },
  {
    action: 0,
    id: 2,
    kodeKaryawan: "K0002",
    namaKaryawan: "MUHAMMAD ADI SAPUTRA",
    jenisKelamin: "L",
    alamat: "TRINILAN RT 007 RW 004 MANGGUNG NGEMPLAK BOYOLALI",
    city: { id: 1615, text: "KAB. BOYOLALI", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "082221075225",
    kTP: "3309110108939004",
    tanggalMasuk: "2016-08-10 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 42640,
      provinceID: 13,
      cityID: 1615,
      zipCode: "57375",
      kelurahan: "Manggung",
      kecamatan: "Ngemplak",
      kabupaten: "KAB. BOYOLALI",
      ahmCode: "3309110011",
      bpsCode: "3309110011",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "BOYOLALI",
    tanggalLahir: "1993-08-01 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 0,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 1,
    nik: "0002",
    listJabatan: [{ jabatanID: 5, jabatan: "Mekanik" }],
    listPayroll: [
      { payrollID: 6, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 7,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 8,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 9,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 10, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: true,
  },
  {
    action: 0,
    id: 1,
    kodeKaryawan: "K0001",
    namaKaryawan: "SULARTO",
    jenisKelamin: "L",
    alamat: "DUKUHAN RT 003 RW 006 BANYUANYAR BANJARSARI SURAKARTA",
    city: { id: 1574, text: "KOTA SURAKARTA", rowStatus: 0, flag: 1 },
    province: {
      id: 13,
      value: "3300",
      provinceCode: "3300",
      text: "JAWA TENGAH",
    },
    noTelepon: "",
    noHP: "082146103758",
    kTP: "3372050107750004",
    tanggalMasuk: "2014-06-11 00:00:00",
    tanggalBerhenti: "3000-12-31 00:00:00",
    area: {
      id: 37374,
      provinceID: 13,
      cityID: 1574,
      zipCode: "57137",
      kelurahan: "Banyuanyar",
      kecamatan: "Banjarsari",
      kabupaten: "KOTA SURAKARTA",
      ahmCode: "3372050013",
      bpsCode: "3372050013",
      rowStatus: 0,
    },
    email: "",
    catatan: "",
    tempatLahir: "surakarta",
    tanggalLahir: "1975-07-01 00:00:00",
    agama: 1,
    berlakuKTP: "3000-12-31 00:00:00",
    kebangsaan: 1,
    statusKawin: 0,
    statusKaryawan: 0,
    statusKomisi: 0,
    tipeKomisi: 0,
    satuanKomisi: "0",
    nilaiKomisi: 0.0,
    statusPIT: 1,
    nik: "001",
    listJabatan: [{ jabatanID: 5, jabatan: "Mekanik" }],
    listPayroll: [
      { payrollID: 1, gaji: "Gaji Pokok", nilaiGaji: 0.0, aktif: true },
      {
        payrollID: 2,
        gaji: "Tunjangan Jabatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 3,
        gaji: "Tunjangan Kesehatan",
        nilaiGaji: 0.0,
        aktif: true,
      },
      {
        payrollID: 4,
        gaji: "Tunjangan Transport",
        nilaiGaji: 0.0,
        aktif: true,
      },
      { payrollID: 5, gaji: "Uang Harian", nilaiGaji: 0.0, aktif: true },
    ],
    listTraining: [],
    aktif: true,
  },
];

export function convertData(data: any) {
  return data.map((item: any) => ({
    name: item.namaKaryawan,
    alamat: item.alamat,
    provinsi: item.province.text,
    kabupaten: item.city.text,
    kecamatan: item.area.kecamatan,
    kelurahan: item.area.kelurahan,
    kodepos: item.area.zipCode,
    notelp: item.noTelepon,
    nohp: item.noHP,
    email: item.email,
    catatan: item.catatan,
    noktp: item.kTP,
    tempat_lahir: item.tempatLahir,
    tanggal_lahir: new Date(item.tanggalLahir),
    gender: item.jenisKelamin,
    agama: "islam", // You need to map agama value to corresponding string
    berlaku_hingga: new Date(item.berlakuKTP),
    status_kawin: "kawin", // You need to map statusKawin value to corresponding string
    status_kebangsaan: "wna", // You need to map kebangsaan value to corresponding string
    status_karyawan_tetap: "tidak tetap", // You need to map statusKaryawan value to corresponding string
    honda_id: item.id.toString(),
    tanggal_masuk: new Date(item.tanggalMasuk),
    tanggal_berhenti: new Date(item.tanggalBerhenti),
    jabatan: item.listJabatan[0]?.jabatan || "",
    level_training: "0", // You need to map listTraining to corresponding string
    status_pit: "non pit", // You need to map statusPIT value to corresponding string
    komisi_penjualan: "tidak aktif", // You need to map statusKomisi value to corresponding string
    gaji_pokok:
      item.listPayroll.find((payroll: any) => payroll.gaji === "Gaji Pokok")
        ?.nilaiGaji || 0,
    tunjangan_jabatan:
      item.listPayroll.find(
        (payroll: any) => payroll.gaji === "Tunjangan Jabatan",
      )?.nilaiGaji || 0,
    kesehatan:
      item.listPayroll.find(
        (payroll: any) => payroll.gaji === "Tunjangan Kesehatan",
      )?.nilaiGaji || 0,
    transport:
      item.listPayroll.find(
        (payroll: any) => payroll.gaji === "Tunjangan Transport",
      )?.nilaiGaji || 0,
    uang_harian:
      item.listPayroll.find((payroll: any) => payroll.gaji === "Uang Harian")
        ?.nilaiGaji || 0,
  }));
}

const convertedData = convertData(data);
console.log(convertedData);

